import Head from "next/head";

import HomeView from "../view/home";
import { GetServerSideProps, NextPage } from "next";

import { Projects, Skills } from "../mock/project";
import { Box, Text } from "@chakra-ui/react";
import { Project, ProjectsProps, Skill, SkillsProps } from "../@types";
import project from "./project/[id]";

// eslint-disable-next-line react/prop-types
interface Homeprops{
    project:ProjectsProps
    skill:SkillsProps
}
const Home: NextPage = (props) => {
    return (
        <>
            <Head>
                <title>Lucas Paiva</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HomeView skills={props.skill} project={props.project} />
            <Box bg="gray.700" color="white" p={4} mt="10px">
                <Text>Copyright © {new Date().getFullYear()} My Company</Text>
            </Box>
        </>
    );
};
export default Home;

export const getServerSideProps: GetServerSideProps = async () => {
    const skill = Skills;
    const project = Projects;

    return {
        props: {
            project,
            skill,
        },
    };
};
