import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import HomeView  from "../view/home";
import { NextPage } from "next";



const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Lucas Paiva</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HomeView/>
        </>
    );
};
export default Home;
